### PR TITLE
Enable testnet key generation

### PR DESCRIPTION
**Pull request by gbizzotto**
All that was missing was the command line option.

### CODE REVIEW

**Comment by prusnak** [comment]
Thanks!

**Comment by gbizzotto** [comment]
I forgot to update readme.rst /:

**Comment by prusnak** [comment]
Push or push force into your branch, I will accept it.

**Comment by gbizzotto** [comment]
I pushed it into my branch. Not sure if I should make another pull request though.

**Comment by prusnak** [comment]
Not needed. Applied, Thanks!

**Comment by gbizzotto** [comment]
Cool! Thanks to you and all the contributors.

**Pull request merged**
